### ISSUE TITLE
missing jdmp-libsvn

### ISSUE THREAD

**Issue by antosamalona** [jdmp/java-data-mining-package#1]
Hello there jdmp Developers!
I get problem missing org.jdmp:jdmp-libsvn after downloading using maven.
How do I fix this?

**Comment by holger-arndt** [comment]
So this is not about the code from the master branch here on git, but you created your own project and tried to include jdmp in your pom.xml file, right?

In this case you need to include the following for libsvm:

```
<dependency>
    <groupId>org.jdmp</groupId>
    <artifactId>jdmp-libsvm</artifactId>
    <version>0.3.0</version>
</dependency>

```

Then the jar file should get downloaded automatically from Maven.

**Comment by antosamalona** [comment]
Yes, you're right!.
Thanks a lot.

**Comment by antosamalona** [comment]
This is solved! Thank  a lot!
